import { Footer, Navbar, Providers } from "@/components/shared";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { FC } from "react";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Your Song",
  description: "Generated by rakibul-wdp",
};

const RootLayout: FC<Readonly<IChildren>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
