import { Footer, Navbar, Providers } from '@/components/shared'
import type { Metadata } from 'next'
import { Montserrat, Outfit } from 'next/font/google'
import { FC } from 'react'
import './globals.css'

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
})
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Skygate',
  description: 'Generated by rakibul-wdp',
}

const RootLayout: FC<Readonly<IChildren>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${montserrat.variable}`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
